# Generated by Django 4.1 on 2022-11-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_simg_alter_post_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='simg',
            name='jdg',
            field=models.CharField(default='ボタンで判定します', max_length=200),
        ),
    ]
