# Generated by Django 4.1 on 2022-11-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_simg_jdg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='simg',
            name='imgf',
            field=models.ImageField(upload_to=''),
        ),
    ]
